# Generated by Django 5.2.8 on 2025-12-08 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('dashboard', '0004_chiller_latitude_chiller_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='dashboard.cliente'),
        ),
    ]
