# Generated by Django 5.0.6 on 2025-11-05 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(db_column='idcliente', primary_key=True, serialize=False)),
                ('nome', models.TextField(db_column='nome')),
                ('email', models.TextField(db_column='email')),
                ('logo', models.BinaryField(blank=True, null=True)),
                ('telefone', models.TextField(blank=True, null=True)),
                ('localidade', models.TextField(blank=True, null=True)),
                ('nif', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Chiller',
            fields=[
                ('idChiller', models.AutoField(db_column='idchiller', primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('localizacao', models.TextField()),
                ('ipcontrolador', models.TextField()),
                ('status', models.CharField(choices=[('ligado', 'Ligado'), ('desativado', 'Desativado'), ('manutencao', 'Manutenção')], default='ligado', max_length=50)),
                ('marca', models.TextField(blank=True, null=True)),
                ('modelo', models.TextField(blank=True, null=True)),
                ('n_serie', models.TextField(blank=True, null=True)),
                ('gas', models.TextField(blank=True, null=True)),
                ('ciclo', models.CharField(choices=[('verao', 'Verão'), ('inverno', 'Inverno')], default='verao', max_length=20)),
                ('idCliente', models.ForeignKey(db_column='idcliente', on_delete=django.db.models.deletion.CASCADE, related_name='chillers', to='dashboard.cliente')),
            ],
            options={
                'db_table': 'chiller',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClienteChillers',
            fields=[
            ],
            options={
                'verbose_name': 'Cliente com Chillers',
                'verbose_name_plural': 'Clientes com Chillers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dashboard.cliente',),
        ),
    ]
