# Generated by Django 5.2.8 on 2025-11-29 18:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiller',
            name='data_ultima_revisao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Última Revisão'),
        ),
        migrations.AddField(
            model_name='chiller',
            name='horas_funcionamento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Horas de Funcionamento'),
        ),
        migrations.CreateModel(
            name='Intervencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnico_nome', models.CharField(max_length=100, verbose_name='Técnico')),
                ('tipo', models.CharField(choices=[('Preventiva', 'Preventiva'), ('Corretiva', 'Corretiva'), ('Inspeção', 'Inspeção/Rotina'), ('Outro', 'Outro')], max_length=50, verbose_name='Tipo')),
                ('categoria', models.CharField(blank=True, choices=[('Mecânica', 'Mecânica'), ('Elétrica', 'Elétrica'), ('Limpeza', 'Limpeza'), ('Software', 'Software/Parâmetros'), ('Outra', 'Outra')], max_length=50, null=True)),
                ('descricao', models.TextField(verbose_name='Descrição do Serviço')),
                ('data_intervencao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Intervenção')),
                ('custo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo (€)')),
                ('componentes_substituidos', models.TextField(blank=True, null=True, verbose_name='Peças')),
                ('chiller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervencoes', to='dashboard.chiller', verbose_name='Chiller Associado')),
            ],
            options={
                'db_table': 'intervencao',
                'ordering': ['-data_intervencao'],
                'managed': True,
            },
        ),
    ]
