# Generated by Django 5.2.8 on 2025-11-29 19:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_chiller_data_ultima_revisao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intervencao',
            options={'ordering': ['-data_intervencao']},
        ),
        migrations.AddField(
            model_name='intervencao',
            name='gas_adicionado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Gás Adicionado (kg)'),
        ),
        migrations.AddField(
            model_name='intervencao',
            name='reset_horimetro',
            field=models.BooleanField(default=False, verbose_name='Reset Horas'),
        ),
        migrations.AddField(
            model_name='intervencao',
            name='teste_fugas_realizado',
            field=models.BooleanField(default=False, verbose_name='Teste Fugas'),
        ),
        migrations.AlterField(
            model_name='intervencao',
            name='categoria',
            field=models.CharField(choices=[('Compressores', 'Compressores / Óleo'), ('Circuito Frigorífico', 'Circuito de Gás'), ('Permutadores', 'Limpeza Permutadores'), ('Elétrica', 'Elétrica / Comandos'), ('Hidráulica', 'Hidráulica'), ('Sensores', 'Sensores / Automação')], default='outro', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intervencao',
            name='chiller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervencoes', to='dashboard.chiller'),
        ),
        migrations.AlterField(
            model_name='intervencao',
            name='componentes_substituidos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intervencao',
            name='custo_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='intervencao',
            name='data_intervencao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='intervencao',
            name='descricao',
            field=models.TextField(verbose_name='Relatório Técnico'),
        ),
        migrations.AlterField(
            model_name='intervencao',
            name='tipo',
            field=models.CharField(choices=[('Preventiva', 'Preventiva (Plano)'), ('Corretiva', 'Corretiva (Avaria)'), ('Preditiva', 'Preditiva (Condição)'), ('Regulamentar', 'Legal / F-Gas'), ('Retrofit', 'Melhoria / Retrofit')], max_length=50),
        ),
    ]
