# Generated by Django 5.0.6 on 2025-12-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_intervencao_options_intervencao_gas_adicionado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiller',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='chiller',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Longitude'),
        ),
    ]
